// The canonical, hand-maintained ingredient list — the SINGLE source of truth for the
// stock list, recipe-chip classification, aliases, and umbrella grouping (all derived in
// catalog.ts). Edit freely. A recipe ingredient not found here renders as a plain,
// icon-less chip until you add it.
//
//   cat      — category (drives icon default + stock grouping via sectionFor)
//   aliases  — extra recipe-text names that resolve to this ingredient (identity + citrus
//              juice/peel/wheel forms are derived, so list only real shorthands here)
//   umbrellas— parent ids this is a CHILD of; a key referenced here is an effective generic,
//              hidden from the stock list and satisfied when any child is stocked (overlap ok)

export interface SeedIngredient {
  key: string;
  disp: string;
  cat: string;
  color: string;
  shape: string | null;
  abv: number;
  syrup?: string;
  citrus?: string;
  aliases?: string[];
  umbrellas?: string[];
}

export const INGREDIENTS: SeedIngredient[] = [
  {
    key: "absinthe",
    disp: "Absinthe",
    cat: "spirit",
    color: "#9FCB3B",
    shape: "squircle",
    abv: 0.62,
  },
  {
    key: "amaretto",
    disp: "Amaretto",
    cat: "liqueur",
    color: "#9B5A2A",
    shape: "hexagon",
    abv: 0.24,
  },
  {
    key: "angostura bitters",
    disp: "Angostura bitters",
    cat: "bitters",
    color: "#A8412E",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "aperol",
    disp: "Aperol",
    cat: "liqueur",
    color: "#F4531E",
    shape: "hexagon",
    abv: 0.11,
  },
  {
    key: "apple brandy",
    disp: "Apple brandy",
    cat: "spirit",
    color: "#B86A2A",
    shape: "squircle",
    abv: 0.4,
    aliases: ["calvados"],
    umbrellas: ["brandy"],
  },
  {
    key: "arugula extract",
    disp: "Arugula extract",
    cat: "herb",
    color: "#6B8F3F",
    shape: "dropper",
    abv: 0,
  },
  {
    key: "bailey's",
    disp: "Bailey's",
    cat: "liqueur",
    color: "#CBA980",
    shape: "hexagon",
    abv: 0.17,
  },
  {
    key: "bénédictine",
    disp: "Bénédictine",
    cat: "liqueur",
    color: "#C8902E",
    shape: "hexagon",
    abv: 0.4,
    aliases: ["benedictine"],
  },
  {
    key: "bitters",
    disp: "Bitters",
    cat: "bitters",
    color: "#8A5A33",
    shape: "triangle",
    abv: 0.44,
  },
  {
    key: "blackberry liqueur",
    disp: "Blackberry liqueur",
    cat: "liqueur",
    color: "#4A2540",
    shape: "hexagon",
    abv: 0.2,
    aliases: ["blackberry", "cassis", "mure", "mûre"],
  },
  {
    key: "bourbon",
    disp: "Bourbon",
    cat: "spirit",
    color: "#B5651D",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["whiskey"],
  },
  {
    key: "brandy",
    disp: "Brandy",
    cat: "spirit",
    color: "#A85A2A",
    shape: "squircle",
    abv: 0.4,
  },
  {
    key: "brown sugar",
    disp: "Brown sugar",
    cat: "sugar",
    color: "#9B6B3A",
    shape: "cube",
    abv: 0,
  },
  {
    key: "cachaça",
    disp: "Cachaça",
    cat: "spirit",
    color: "#E1DBAE",
    shape: "squircle",
    abv: 0.4,
    aliases: ["cachaca"],
    umbrellas: ["rum"],
  },
  {
    key: "campari",
    disp: "Campari",
    cat: "liqueur",
    color: "#C3122E",
    shape: "hexagon",
    abv: 0.24,
  },
  {
    key: "candied ginger",
    disp: "Candied ginger",
    cat: "other",
    color: "#C99A3B",
    shape: "ginger",
    abv: 0,
  },
  {
    key: "cardamom bitters",
    disp: "Cardamom bitters",
    cat: "bitters",
    color: "#7E8B4A",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "champagne",
    disp: "Champagne",
    cat: "fortified",
    color: "#E8E2B0",
    shape: "glass",
    abv: 0.12,
    aliases: ["prosecco", "sparkling"],
    umbrellas: ["wine"],
  },
  {
    key: "cherry",
    disp: "Cherry",
    cat: "fruit",
    color: "#B5293A",
    shape: "cherry",
    abv: 0,
  },
  {
    key: "chocolate bitters",
    disp: "Chocolate bitters",
    cat: "bitters",
    color: "#5A3520",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "cinnamon syrup",
    disp: "Cinnamon syrup",
    cat: "syrup",
    color: "#8A4B2A",
    shape: "bottle",
    abv: 0,
    syrup: "cinnamon",
    aliases: ["cinnamon"],
    umbrellas: ["syrup"],
  },
  {
    key: "coconut cream",
    disp: "Coconut cream",
    cat: "other",
    color: "#F2EAD8",
    shape: "droplet",
    abv: 0,
    aliases: ["coconut"],
  },
  {
    key: "cognac",
    disp: "Cognac",
    cat: "spirit",
    color: "#9B4D1E",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["brandy"],
  },
  {
    key: "cranberry",
    disp: "Cranberry juice",
    cat: "fruit",
    color: "#B5293A",
    shape: "droplet",
    abv: 0,
  },
  {
    key: "crème de cacao",
    disp: "Crème de cacao",
    cat: "liqueur",
    color: "#5A3A29",
    shape: "hexagon",
    abv: 0.24,
    aliases: ["cacao"],
  },
  {
    key: "crème de violette",
    disp: "Crème de violette",
    cat: "liqueur",
    color: "#7A4FA3",
    shape: "hexagon",
    abv: 0.2,
    aliases: ["violet", "violette"],
  },
  {
    key: "dark rum",
    disp: "Dark rum",
    cat: "spirit",
    color: "#6E3F1C",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["rum"],
  },
  {
    key: "dry vermouth",
    disp: "Dry vermouth",
    cat: "fortified",
    color: "#D7D1A0",
    shape: "glass",
    abv: 0.17,
    umbrellas: ["vermouth", "wine"],
  },
  {
    key: "egg",
    disp: "Egg",
    cat: "egg",
    color: "#F2EEE0",
    shape: "egg",
    abv: 0,
    aliases: ["egg white"],
  },
  {
    key: "elderflower liqueur",
    disp: "Elderflower liqueur",
    cat: "liqueur",
    color: "#E6E0AE",
    shape: "hexagon",
    abv: 0.2,
    aliases: ["elderflower", "germain"],
  },
  {
    key: "espresso",
    disp: "Espresso",
    cat: "other",
    color: "#3A2417",
    shape: "droplet",
    abv: 0,
  },
  {
    key: "falernum",
    disp: "Falernum",
    cat: "liqueur",
    color: "#D9C28A",
    shape: "hexagon",
    abv: 0.11,
  },
  {
    key: "gin",
    disp: "Gin",
    cat: "spirit",
    color: "#DCEAF0",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["spirit", "gin"],
  },
  {
    key: "ginger beer",
    disp: "Ginger beer",
    cat: "soda",
    color: "#C9A24B",
    shape: "droplet",
    abv: 0,
  },
  {
    key: "ginger extract",
    disp: "Ginger extract",
    cat: "other",
    color: "#C99A3B",
    shape: "dropper",
    abv: 0,
  },
  {
    key: "grapefruit",
    disp: "Grapefruit",
    cat: "citrus",
    color: "#E8806B",
    shape: "circle",
    abv: 0,
    citrus: "grapefruit",
  },
  {
    key: "green chartreuse",
    disp: "Green Chartreuse",
    cat: "liqueur",
    color: "#3E7A33",
    shape: "hexagon",
    abv: 0.55,
    umbrellas: ["chartreuse"],
  },
  {
    key: "honey syrup",
    disp: "Honey syrup",
    cat: "syrup",
    color: "#D6A93B",
    shape: "bottle",
    abv: 0,
    syrup: "honey",
    aliases: ["honey"],
    umbrellas: ["syrup"],
  },
  {
    key: "jamaican rum",
    disp: "Jamaican rum",
    cat: "spirit",
    color: "#8A4B1E",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["rum"],
  },
  {
    key: "kahlúa",
    disp: "Kahlúa",
    cat: "liqueur",
    color: "#3A2417",
    shape: "hexagon",
    abv: 0.2,
    aliases: ["coffee liqueur", "kahlua"],
  },
  {
    key: "lapsang syrup",
    disp: "Lapsang syrup",
    cat: "syrup",
    color: "#5C3A24",
    shape: "bottle",
    abv: 0,
    syrup: "lapsang",
    aliases: ["lapsang"],
    umbrellas: ["syrup"],
  },
  {
    key: "lemon",
    disp: "Lemon",
    cat: "citrus",
    color: "#E6C84B",
    shape: "circle",
    abv: 0,
    citrus: "lemon",
  },
  {
    key: "light rum",
    disp: "Light rum",
    cat: "spirit",
    color: "#E6D7A6",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["rum", "spirit"],
  },
  {
    key: "lillet blanc",
    disp: "Lillet Blanc",
    cat: "fortified",
    color: "#E6D98A",
    shape: "glass",
    abv: 0.17,
    umbrellas: ["wine"],
  },
  {
    key: "lime",
    disp: "Lime",
    cat: "citrus",
    color: "#8FBF3F",
    shape: "circle",
    abv: 0,
    citrus: "lime",
  },
  {
    key: "luxardo",
    disp: "Luxardo",
    cat: "liqueur",
    color: "#E7E1D2",
    shape: "hexagon",
    abv: 0.32,
    aliases: ["maraschino"],
  },
  {
    key: "maple syrup",
    disp: "Maple syrup",
    cat: "syrup",
    color: "#B5651D",
    shape: "bottle",
    abv: 0,
    syrup: "maple",
    umbrellas: ["syrup"],
  },
  {
    key: "milk",
    disp: "Milk",
    cat: "dairy",
    color: "#F0EDE3",
    shape: "droplet",
    abv: 0,
  },
  {
    key: "mint",
    disp: "Mint",
    cat: "herb",
    color: "#6FAE4B",
    shape: "sprig",
    abv: 0,
  },
  {
    key: "nutmeg",
    disp: "Nutmeg",
    cat: "spice",
    color: "#8A5A2A",
    shape: "seed",
    abv: 0,
  },
  {
    key: "orange",
    disp: "Orange",
    cat: "citrus",
    color: "#E0892B",
    shape: "circle",
    abv: 0,
    citrus: "orange",
  },
  {
    key: "orange bitters",
    disp: "Orange bitters",
    cat: "bitters",
    color: "#E0892B",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "orange curaçao",
    disp: "Orange Curaçao",
    cat: "liqueur",
    color: "#E0892B",
    shape: "hexagon",
    abv: 0.4,
    aliases: ["cointreau", "curacao", "curaçao", "triple sec"],
  },
  {
    key: "orgeat",
    disp: "Orgeat",
    cat: "syrup",
    color: "#E6DAB8",
    shape: "bottle",
    abv: 0,
    syrup: "orgeat",
    umbrellas: ["syrup"],
  },
  {
    key: "passion fruit liqueur",
    disp: "Passion fruit liqueur",
    cat: "liqueur",
    color: "#E8852B",
    shape: "hexagon",
    abv: 0.18,
    aliases: ["passionfruit liqueur"],
  },
  {
    key: "peach bitters",
    disp: "Peach bitters",
    cat: "bitters",
    color: "#E6A968",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "peychaud bitters",
    disp: "Peychaud bitters",
    cat: "bitters",
    color: "#D14B3A",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "pineapple",
    disp: "Pineapple juice",
    cat: "mixer",
    color: "#E8C13A",
    shape: "droplet",
    abv: 0,
  },
  {
    key: "pomegranate",
    disp: "Pomegranate juice",
    cat: "fruit",
    color: "#9E2A3A",
    shape: "droplet",
    abv: 0,
  },
  {
    key: "raspberry",
    disp: "Raspberry",
    cat: "fruit",
    color: "#B02A4A",
    shape: "berry",
    abv: 0,
  },
  {
    key: "red wine",
    disp: "Red wine",
    cat: "fortified",
    color: "#6E1F2E",
    shape: "glass",
    abv: 0.13,
    umbrellas: ["wine"],
  },
  {
    key: "rum",
    disp: "Rum",
    cat: "spirit",
    color: "#C99A5B",
    shape: "squircle",
    abv: 0.4,
  },
  {
    key: "rye",
    disp: "Rye",
    cat: "spirit",
    color: "#C06A22",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["whiskey"],
  },
  {
    key: "saline solution",
    disp: "Saline solution",
    cat: "other",
    color: "#DDE6EC",
    shape: "dropper",
    abv: 0,
    aliases: ["saline"],
  },
  {
    key: "scotch",
    disp: "Scotch",
    cat: "spirit",
    color: "#A85A1A",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["whiskey"],
  },
  {
    key: "simple syrup",
    disp: "Simple syrup",
    cat: "syrup",
    color: "#DDE2E6",
    shape: "bottle",
    abv: 0,
    syrup: "simple",
    aliases: ["simple"],
    umbrellas: ["syrup"],
  },
  {
    key: "soda water",
    disp: "Soda water",
    cat: "soda",
    color: "#DCE8EE",
    shape: "droplet",
    abv: 0,
    aliases: ["seltzer", "soda"],
  },
  {
    key: "spirit",
    disp: "Neutral spirit",
    cat: "spirit",
    color: "#E0E6EC",
    shape: "squircle",
    abv: 0.4,
  },
  {
    key: "sweet vermouth",
    disp: "Sweet vermouth",
    cat: "fortified",
    color: "#7A2E2E",
    shape: "glass",
    abv: 0.17,
    umbrellas: ["vermouth", "wine"],
  },
  {
    key: "syrup",
    disp: "Syrup",
    cat: "syrup",
    color: "#C9B98A",
    shape: "bottle",
    abv: 0,
    syrup: "generic",
  },
  {
    key: "tequila",
    disp: "Tequila",
    cat: "spirit",
    color: "#E6E0AE",
    shape: "squircle",
    abv: 0.4,
    aliases: ["mezcal"],
    umbrellas: ["tequila"],
  },
  {
    key: "tonic water",
    disp: "Tonic water",
    cat: "soda",
    color: "#DCE8EE",
    shape: "droplet",
    abv: 0,
    aliases: ["tonic"],
  },
  {
    key: "whiskey",
    disp: "Whiskey",
    cat: "spirit",
    color: "#B5651D",
    shape: "squircle",
    abv: 0.4,
    aliases: ["whisky"],
  },
  {
    key: "wine",
    disp: "Wine",
    cat: "fortified",
    color: "#7A2E3A",
    shape: "glass",
    abv: 0.12,
  },
  {
    key: "yellow chartreuse",
    disp: "Yellow Chartreuse",
    cat: "liqueur",
    color: "#D7C23A",
    shape: "hexagon",
    abv: 0.4,
    umbrellas: ["chartreuse"],
  },
];
