// The canonical, hand-maintained ingredient list — the SINGLE source of truth for the
// stock list, recipe-chip classification, aliases, and umbrella grouping (all derived in
// catalog.ts). Edit freely. A recipe ingredient not found here renders as a plain,
// icon-less chip until you add it.
//
//   cat      — category (drives icon default + stock grouping via sectionFor)
//   aliases  — extra recipe-text names that resolve to this ingredient (identity + citrus
//              juice/peel/wheel forms are derived, so list only real shorthands here)
//   umbrellas— parent ids this is a CHILD of; a key referenced here is an effective generic,
//              hidden from the stock list and satisfied when any child is stocked (overlap ok)

import type { Form } from '../core/types';

export interface SeedIngredient {
  key: string;
  disp: string;
  cat: string;
  color: string;
  shape: string | null;
  abv: number;
  syrup?: string;
  citrus?: string;
  aliases?: string[];
  /** Aliases that resolve only in one parse context. A scoped alias shadows another
   *  entry's identity key in its context (cocktail "honey" → honey syrup, while food
   *  "honey" stays the raw honey entry) — see buildAliasIndex in catalog.ts. */
  cocktailAliases?: string[];
  foodAliases?: string[];
  umbrellas?: string[];
  /** Trailing forms this ingredient takes (citrus wedge/peel/…). Omit to inherit the
   *  category default — citrus/bitters synthesise theirs. A form's `unit` registers a
   *  count-unit ("sprig","slice") globally. */
  forms?: Form[];
  /** Default physical location override. Rarely set — the category default
   *  (defaultLocationForCat) covers almost everything; present only for the odd
   *  bottle whose default should differ from its category. */
  defaultLocation?: string;
}

export const INGREDIENTS: SeedIngredient[] = [
  {
    key: "absinthe",
    disp: "Absinthe",
    cat: "spirit",
    color: "#9FCB3B",
    shape: "squircle",
    abv: 0.62,
  },
  {
    key: "almond milk",
    disp: "Almond milk",
    cat: "dairyegg",
    color: "#EAE3CE",
    shape: "droplet",
    abv: 0,
  },
  {
    key: "amaretto",
    disp: "Amaretto",
    cat: "liqueur",
    color: "#9B5A2A",
    shape: "hexagon",
    abv: 0.24,
  },
  {
    key: "angostura bitters",
    disp: "Angostura bitters",
    cat: "bitters",
    color: "#A8412E",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "aperol",
    disp: "Aperol",
    cat: "liqueur",
    color: "#F4531E",
    shape: "hexagon",
    abv: 0.11,
  },
  {
    key: "apple brandy",
    disp: "Apple brandy",
    cat: "spirit",
    color: "#B86A2A",
    shape: "squircle",
    abv: 0.4,
    aliases: ["calvados"],
    umbrellas: ["brandy"],
  },
  {
    key: "arugula extract",
    disp: "Arugula extract",
    cat: "extract",
    color: "#6B8F3F",
    shape: "dropper",
    abv: 0,
  },
  {
    key: "avocado",
    disp: "Avocado",
    cat: "produce",
    color: "#7A9B4A",
    shape: "avocado",
    abv: 0,
    aliases: ["avocados"],
  },
  {
    key: "bailey's",
    disp: "Bailey's",
    cat: "liqueur",
    color: "#CBA980",
    shape: "hexagon",
    abv: 0.17,
  },
  {
    key: "beer",
    disp: "Beer",
    cat: "brew",
    color: "#C9881F",
    shape: "can",
    abv: 0.05,
    umbrellas: ["consumable"],
  },
  {
    key: "bell pepper",
    disp: "Bell pepper",
    cat: "produce",
    color: "#C0512E",
    shape: "pepper",
    abv: 0,
    aliases: ["bell peppers"],
  },
  {
    key: "bénédictine",
    disp: "Bénédictine",
    cat: "liqueur",
    color: "#C8902E",
    shape: "hexagon",
    abv: 0.4,
    aliases: ["benedictine"],
  },
  {
    key: "bitters",
    disp: "Bitters",
    cat: "bitters",
    color: "#8A5A33",
    shape: "triangle",
    abv: 0.44,
  },
  {
    key: "black pepper",
    disp: "Black pepper",
    cat: "herbspice",
    color: "#4A4238",
    shape: "shaker",
    abv: 0,
    aliases: ["pepper"],
  },
  {
    key: "blackberry liqueur",
    disp: "Blackberry liqueur",
    cat: "liqueur",
    color: "#4A2540",
    shape: "hexagon",
    abv: 0.2,
    aliases: ["blackberry", "cassis", "mure", "mûre"],
  },
  {
    key: "bourbon",
    disp: "Bourbon",
    cat: "spirit",
    color: "#B5651D",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["whiskey"],
  },
  {
    key: "brandy",
    disp: "Brandy",
    cat: "spirit",
    color: "#A85A2A",
    shape: "squircle",
    abv: 0.4,
  },
  {
    key: "bread",
    disp: "Bread",
    cat: "bakery",
    color: "#C2904E",
    shape: "loaf",
    abv: 0,
  },
  {
    key: "brown sugar",
    disp: "Brown sugar",
    cat: "sugar",
    color: "#9B6B3A",
    shape: "cube",
    abv: 0,
  },
  {
    key: "buns",
    disp: "Buns",
    cat: "bakery",
    color: "#C99A6B",
    shape: "loaf",
    abv: 0,
    aliases: ["bun"],
  },
  {
    key: "buttermilk",
    disp: "Buttermilk",
    cat: "dairyegg",
    color: "#EFEADF",
    shape: "droplet",
    abv: 0,
  },
  {
    key: "cachaça",
    disp: "Cachaça",
    cat: "spirit",
    color: "#E1DBAE",
    shape: "squircle",
    abv: 0.4,
    aliases: ["cachaca"],
    umbrellas: ["cane"],
  },
  {
    key: "campari",
    disp: "Campari",
    cat: "liqueur",
    color: "#C3122E",
    shape: "hexagon",
    abv: 0.24,
  },
  {
    key: "candied ginger",
    disp: "Candied ginger",
    cat: "other",
    color: "#C99A3B",
    shape: "ginger",
    abv: 0,
    forms: [{ keyword: "", role: "count", unit: "piece", process: "garnish" }],
  },
  {
    key: "cardamom bitters",
    disp: "Cardamom bitters",
    cat: "bitters",
    color: "#7E8B4A",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "cereal",
    disp: "Cereal",
    cat: "drygood",
    color: "#C9881F",
    shape: "box",
    abv: 0,
  },
  {
    key: "champagne",
    disp: "Champagne",
    cat: "fortified",
    color: "#E8E2B0",
    shape: "glass",
    abv: 0.12,
    aliases: ["prosecco", "sparkling"],
    umbrellas: ["wine", "consumable"],
  },
  {
    key: "cheese slices",
    disp: "Cheese slices",
    cat: "dairyegg",
    color: "#E8B84A",
    shape: "cheese",
    abv: 0,
    aliases: ["sliced cheese"],
  },
  {
    key: "cherry",
    disp: "Cherry",
    cat: "fruit",
    color: "#B5293A",
    shape: "cherry",
    abv: 0,
    forms: [{ keyword: "", role: "count", process: "garnish" }],
  },
  {
    key: "chili powder",
    disp: "Chili powder",
    cat: "herbspice",
    color: "#A8412E",
    shape: "shaker",
    abv: 0,
  },
  {
    key: "chips",
    disp: "Chips",
    cat: "snack",
    color: "#D9A93B",
    shape: "bag",
    abv: 0,
  },
  {
    key: "chocolate bitters",
    disp: "Chocolate bitters",
    cat: "bitters",
    color: "#5A3520",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "chocolate sauce",
    disp: "Chocolate sauce",
    cat: "condiment",
    color: "#5A3520",
    shape: "squeeze",
    abv: 0,
  },
  {
    key: "cider",
    disp: "Cider",
    cat: "brew",
    color: "#C99A3B",
    shape: "can",
    abv: 0.05,
    umbrellas: ["consumable"],
  },
  {
    key: "cinnamon syrup",
    disp: "Cinnamon syrup",
    cat: "syrup",
    color: "#8A4B2A",
    shape: "bottle",
    abv: 0,
    syrup: "cinnamon",
    aliases: ["cinnamon"],
    umbrellas: ["syrup"],
  },
  {
    key: "coconut cream",
    disp: "Coconut cream",
    cat: "other",
    color: "#F2EAD8",
    shape: "droplet",
    abv: 0,
    aliases: ["coconut"],
  },
  {
    key: "coffee",
    disp: "Coffee",
    cat: "drygood",
    color: "#4A2E1C",
    shape: "bag",
    abv: 0,
  },
  {
    key: "cognac",
    disp: "Cognac",
    cat: "spirit",
    color: "#9B4D1E",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["brandy"],
  },
  {
    key: "cold brew",
    disp: "Cold brew",
    cat: "mixer",
    color: "#2E1F14",
    shape: "droplet",
    abv: 0,
    umbrellas: ["consumable"],
  },
  {
    key: "cornmeal",
    disp: "Cornmeal",
    cat: "drygood",
    color: "#D9C28A",
    shape: "bag",
    abv: 0,
    aliases: ["corn meal"],
  },
  {
    key: "cranberry",
    disp: "Cranberry juice",
    cat: "mixer",
    color: "#B5293A",
    shape: "droplet",
    abv: 0,
    umbrellas: ["consumable"],
  },
  {
    key: "crema",
    disp: "Crema",
    cat: "dairyegg",
    color: "#F2EAD8",
    shape: "droplet",
    abv: 0,
  },
  {
    key: "crème de cacao",
    disp: "Crème de cacao",
    cat: "liqueur",
    color: "#5A3A29",
    shape: "hexagon",
    abv: 0.24,
    aliases: ["cacao"],
  },
  {
    key: "crème de violette",
    disp: "Crème de violette",
    cat: "liqueur",
    color: "#7A4FA3",
    shape: "hexagon",
    abv: 0.2,
    aliases: ["violet", "violette"],
  },
  {
    key: "cumin",
    disp: "Cumin",
    cat: "herbspice",
    color: "#8A6B3A",
    shape: "shaker",
    abv: 0,
  },
  {
    key: "dark rum",
    disp: "Dark rum",
    cat: "spirit",
    color: "#6E3F1C",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["rum", "cane"],
  },
  {
    key: "dry vermouth",
    disp: "Dry vermouth",
    cat: "fortified",
    color: "#D7D1A0",
    shape: "glass",
    abv: 0.17,
    umbrellas: ["vermouth", "wine"],
  },
  {
    key: "egg",
    disp: "Egg",
    cat: "dairyegg",
    color: "#F2EEE0",
    shape: "egg",
    abv: 0,
    aliases: ["eggs"],
    // Egg is a bare-count item; the white/yolk modifiers are trailing forms that show
    // the keyword in the name ("Egg white") rather than padding the amount ("1 white").
    forms: [
      { keyword: "", role: "count" },
      { keyword: "white", role: "count", disp: "asis" },
      { keyword: "yolk", role: "count", disp: "asis" },
    ],
  },
  {
    key: "elderflower liqueur",
    disp: "Elderflower liqueur",
    cat: "liqueur",
    color: "#E6E0AE",
    shape: "hexagon",
    abv: 0.2,
    aliases: ["elderflower", "germain"],
  },
  {
    key: "espresso",
    disp: "Espresso",
    cat: "other",
    color: "#3A2417",
    shape: "droplet",
    abv: 0,
    umbrellas: ["consumable"],
  },
  {
    key: "falafel mix",
    disp: "Falafel mix",
    cat: "drygood",
    color: "#B89B5A",
    shape: "box",
    abv: 0,
  },
  {
    key: "falernum",
    disp: "Falernum",
    cat: "liqueur",
    color: "#D9C28A",
    shape: "hexagon",
    abv: 0.11,
  },
  {
    key: "flour",
    disp: "Flour",
    cat: "drygood",
    color: "#E8E2D0",
    shape: "bag",
    abv: 0,
  },
  {
    key: "garlic powder",
    disp: "Garlic powder",
    cat: "herbspice",
    color: "#E0D9C2",
    shape: "shaker",
    abv: 0,
  },
  {
    key: "garlic spread",
    disp: "Garlic spread",
    cat: "condiment",
    color: "#EDE3A2",
    shape: "jar",
    abv: 0,
  },
  {
    key: "gin",
    disp: "Gin",
    cat: "spirit",
    color: "#DCEAF0",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["spirit", "gin"],
  },
  {
    key: "ginger beer",
    disp: "Ginger beer",
    cat: "mixer",
    color: "#C9A24B",
    shape: "droplet",
    abv: 0,
    umbrellas: ["consumable"],
  },
  {
    key: "ginger extract",
    disp: "Ginger extract",
    cat: "extract",
    color: "#C99A3B",
    shape: "dropper",
    abv: 0,
  },
  {
    key: "granola bars",
    disp: "Granola bars",
    cat: "snack",
    color: "#A87B3F",
    shape: "box",
    abv: 0,
    aliases: ["granola bar"],
  },
  {
    key: "grapefruit",
    disp: "Grapefruit",
    cat: "citrus",
    color: "#E8806B",
    shape: "circle",
    abv: 0,
    citrus: "grapefruit",
    aliases: ["grapefruits"],
  },
  {
    key: "green chartreuse",
    disp: "Green Chartreuse",
    cat: "liqueur",
    color: "#3E7A33",
    shape: "hexagon",
    abv: 0.55,
    umbrellas: ["chartreuse"],
  },
  {
    key: "heavy cream",
    disp: "Heavy cream",
    cat: "dairyegg",
    color: "#F2EEE0",
    shape: "droplet",
    abv: 0,
  },
  {
    // Raw pantry honey — distinct stockable from the made syrup. In cocktail context
    // "honey" still means honey syrup (its cocktailAlias shadows this identity).
    key: "honey",
    disp: "Honey",
    cat: "condiment",
    color: "#D6A93B",
    shape: "droplet",
    abv: 0,
    defaultLocation: "pantry",
  },
  {
    key: "honey syrup",
    disp: "Honey syrup",
    cat: "syrup",
    color: "#D6A93B",
    shape: "bottle",
    abv: 0,
    syrup: "honey",
    cocktailAliases: ["honey"],
    umbrellas: ["syrup"],
  },
  {
    key: "hot chili",
    disp: "Hot chili",
    cat: "produce",
    color: "#B5293A",
    shape: "pepper",
    abv: 0,
    aliases: ["hot chilis", "hot chiles", "hot chilies"],
  },
  {
    key: "hot sauce",
    disp: "Hot sauce",
    cat: "condiment",
    color: "#B53A2E",
    shape: "squeeze",
    abv: 0,
  },
  {
    key: "ice cream",
    disp: "Ice cream",
    cat: "dairyegg",
    color: "#F2E3C8",
    shape: "cylinder",
    abv: 0,
    defaultLocation: "freezer",
  },
  {
    key: "italian bread",
    disp: "Italian bread",
    cat: "bakery",
    color: "#B5824A",
    shape: "loaf",
    abv: 0,
  },
  {
    key: "jam",
    disp: "Jam",
    cat: "condiment",
    color: "#9E2A3A",
    shape: "jar",
    abv: 0,
  },
  {
    key: "jamaican rum",
    disp: "Jamaican rum",
    cat: "spirit",
    color: "#8A4B1E",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["rum", "cane"],
  },
  {
    key: "kahlúa",
    disp: "Kahlúa",
    cat: "liqueur",
    color: "#3A2417",
    shape: "hexagon",
    abv: 0.2,
    aliases: ["coffee liqueur", "kahlua"],
  },
  {
    key: "ketchup",
    disp: "Ketchup",
    cat: "condiment",
    color: "#C03A2E",
    shape: "squeeze",
    abv: 0,
  },
  {
    key: "lapsang syrup",
    disp: "Lapsang syrup",
    cat: "syrup",
    color: "#5C3A24",
    shape: "bottle",
    abv: 0,
    syrup: "lapsang",
    aliases: ["lapsang"],
    umbrellas: ["syrup"],
  },
  {
    key: "leafy greens",
    disp: "Leafy greens",
    cat: "produce",
    color: "#5E8F3F",
    shape: "leaf",
    abv: 0,
    aliases: ["lettuce", "arugula", "spinach", "greens", "salad greens"],
  },
  {
    key: "lemon",
    disp: "Lemon",
    cat: "citrus",
    color: "#E6C84B",
    shape: "circle",
    abv: 0,
    citrus: "lemon",
    aliases: ["lemons"],
  },
  {
    key: "light rum",
    disp: "Light rum",
    cat: "spirit",
    color: "#E6D7A6",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["rum", "cane", "spirit"],
  },
  {
    key: "lillet blanc",
    disp: "Lillet Blanc",
    cat: "fortified",
    color: "#E6D98A",
    shape: "glass",
    abv: 0.17,
    umbrellas: ["wine"],
  },
  {
    key: "lime",
    disp: "Lime",
    cat: "citrus",
    color: "#8FBF3F",
    shape: "circle",
    abv: 0,
    citrus: "lime",
    aliases: ["limes"],
  },
  {
    key: "luxardo",
    disp: "Luxardo",
    cat: "liqueur",
    color: "#E7E1D2",
    shape: "hexagon",
    abv: 0.32,
    aliases: ["maraschino"],
  },
  {
    key: "maple syrup",
    disp: "Maple syrup",
    cat: "syrup",
    color: "#B5651D",
    shape: "bottle",
    abv: 0,
    syrup: "maple",
    umbrellas: ["syrup"],
  },
  {
    key: "mayonnaise",
    disp: "Mayonnaise",
    cat: "condiment",
    color: "#F0EDE3",
    shape: "jar",
    abv: 0,
    aliases: ["mayo"],
  },
  {
    key: "mexican cheese blend",
    disp: "Mexican cheese blend",
    cat: "dairyegg",
    color: "#E8A93A",
    shape: "cheese",
    abv: 0,
    aliases: ["shredded mexican cheese blend"],
  },
  {
    key: "milk",
    disp: "Milk",
    cat: "dairyegg",
    color: "#F0EDE3",
    shape: "droplet",
    abv: 0,
  },
  {
    key: "mint",
    disp: "Mint",
    cat: "herbspice",
    color: "#6FAE4B",
    shape: "sprig",
    abv: 0,
    forms: [{ keyword: "", role: "count", unit: "sprig", process: "garnish" }],
  },
  {
    key: "mushroom",
    disp: "Mushroom",
    cat: "produce",
    color: "#B9A584",
    shape: "mushroom",
    abv: 0,
    aliases: ["mushrooms"],
  },
  {
    key: "mustard",
    disp: "Mustard",
    cat: "condiment",
    color: "#D7B23A",
    shape: "bottle",
    abv: 0,
  },
  {
    key: "nutmeg",
    disp: "Nutmeg",
    cat: "herbspice",
    color: "#8A5A2A",
    shape: "seed",
    abv: 0,
    forms: [{ keyword: "", role: "count", unit: "pinch", process: "grate" }],
  },
  {
    key: "olipop",
    disp: "Olipop",
    cat: "mixer",
    color: "#B56A8F",
    shape: "can",
    abv: 0,
    aliases: ["olipops"],
    umbrellas: ["consumable"],
  },
  {
    key: "olive oil",
    disp: "Olive oil",
    cat: "drygood",
    color: "#9B9B3A",
    shape: "bottle",
    abv: 0,
  },
  {
    key: "onion",
    disp: "Onion",
    cat: "produce",
    color: "#C49A55",
    shape: "onion",
    abv: 0,
    aliases: ["onions"],
    defaultLocation: "pantry",
  },
  {
    key: "orange",
    disp: "Orange",
    cat: "citrus",
    color: "#E0892B",
    shape: "circle",
    abv: 0,
    citrus: "orange",
    aliases: ["oranges"],
  },
  {
    key: "orange bitters",
    disp: "Orange bitters",
    cat: "bitters",
    color: "#E0892B",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "orange curaçao",
    disp: "Orange Curaçao",
    cat: "liqueur",
    color: "#E0892B",
    shape: "hexagon",
    abv: 0.4,
    aliases: ["cointreau", "curacao", "curaçao", "triple sec"],
  },
  {
    key: "orgeat",
    disp: "Orgeat",
    cat: "syrup",
    color: "#E6DAB8",
    shape: "bottle",
    abv: 0,
    syrup: "orgeat",
    umbrellas: ["syrup"],
  },
  {
    key: "parmesan cheese",
    disp: "Parmesan cheese",
    cat: "dairyegg",
    color: "#E6D7A6",
    shape: "cheese",
    abv: 0,
    aliases: ["parmesan", "parm", "shaved parm"],
  },
  {
    key: "passion fruit liqueur",
    disp: "Passion fruit liqueur",
    cat: "liqueur",
    color: "#E8852B",
    shape: "hexagon",
    abv: 0.18,
    aliases: ["passionfruit liqueur"],
  },
  {
    key: "pasta",
    disp: "Pasta",
    cat: "drygood",
    color: "#E0C275",
    shape: "box",
    abv: 0,
  },
  {
    key: "pasta sauce",
    disp: "Pasta sauce",
    cat: "condiment",
    color: "#A8412E",
    shape: "jar",
    abv: 0,
    defaultLocation: "pantry",
  },
  {
    key: "peach bitters",
    disp: "Peach bitters",
    cat: "bitters",
    color: "#E6A968",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "peanut butter",
    disp: "Peanut butter",
    cat: "condiment",
    color: "#B5773A",
    shape: "jar",
    abv: 0,
    defaultLocation: "pantry",
  },
  {
    key: "pesto",
    disp: "Pesto",
    cat: "condiment",
    color: "#6B8F3F",
    shape: "jar",
    abv: 0,
  },
  {
    key: "peychaud bitters",
    disp: "Peychaud bitters",
    cat: "bitters",
    color: "#D14B3A",
    shape: "triangle",
    abv: 0.44,
    umbrellas: ["bitters"],
  },
  {
    key: "pickles",
    disp: "Pickles",
    cat: "condiment",
    color: "#708F3F",
    shape: "jar",
    abv: 0,
    aliases: ["pickle"],
  },
  {
    key: "pineapple",
    disp: "Pineapple juice",
    cat: "mixer",
    color: "#E8C13A",
    shape: "droplet",
    abv: 0,
    umbrellas: ["consumable"],
  },
  {
    key: "plant-based breakfast patties",
    disp: "Plant-based breakfast patties",
    cat: "protein",
    color: "#96603A",
    shape: "patty",
    abv: 0,
    aliases: ["maple patties", "breakfast patties"],
  },
  {
    key: "plant-based chicken",
    disp: "Plant-based chicken",
    cat: "protein",
    color: "#DCC9A0",
    shape: "patty",
    abv: 0,
    aliases: ["fake chicken"],
  },
  {
    key: "plant-based crumbles",
    disp: "Plant-based crumbles",
    cat: "protein",
    color: "#7A4B2E",
    shape: "patty",
    abv: 0,
    aliases: ["veggie crumbles"],
  },
  {
    key: "plant-based ground beef",
    disp: "Plant-based ground beef",
    cat: "protein",
    color: "#6E4226",
    shape: "patty",
    abv: 0,
    aliases: ["fake beef"],
  },
  {
    key: "plant-based lunchmeat",
    disp: "Plant-based lunchmeat",
    cat: "protein",
    color: "#C99A8A",
    shape: "patty",
    abv: 0,
    aliases: ["lunchmeat"],
    defaultLocation: "fridge",
  },
  {
    key: "plant-based meatballs",
    disp: "Plant-based meatballs",
    cat: "protein",
    color: "#8A4B33",
    shape: "patty",
    abv: 0,
    aliases: ["veggie meatballs"],
  },
  {
    key: "poblano",
    disp: "Poblano",
    cat: "produce",
    color: "#3E6B33",
    shape: "pepper",
    abv: 0,
    aliases: ["poblanos"],
  },
  {
    key: "pomegranate",
    disp: "Pomegranate juice",
    cat: "mixer",
    color: "#9E2A3A",
    shape: "droplet",
    abv: 0,
    umbrellas: ["consumable"],
  },
  {
    key: "potato",
    disp: "Potato",
    cat: "produce",
    color: "#C2A36B",
    shape: "ellipse",
    abv: 0,
    aliases: ["potatoes"],
    defaultLocation: "pantry",
  },
  {
    key: "queso fresco",
    disp: "Queso fresco",
    cat: "dairyegg",
    color: "#EFE9DC",
    shape: "cheese",
    abv: 0,
  },
  {
    key: "raspberry",
    disp: "Raspberry",
    cat: "fruit",
    color: "#B02A4A",
    shape: "berry",
    abv: 0,
    forms: [{ keyword: "", role: "count", process: "garnish" }],
  },
  {
    key: "red wine",
    disp: "Red wine",
    cat: "fortified",
    color: "#6E1F2E",
    shape: "glass",
    abv: 0.13,
    umbrellas: ["wine", "consumable"],
  },
  {
    key: "refried beans",
    disp: "Refried beans",
    cat: "drygood",
    color: "#8A5A33",
    shape: "cylinder",
    abv: 0,
  },
  {
    key: "rice",
    disp: "Rice",
    cat: "drygood",
    color: "#EDE8D8",
    shape: "bag",
    abv: 0,
  },
  {
    key: "rum",
    disp: "Rum",
    cat: "spirit",
    color: "#C99A5B",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["cane"],
  },
  {
    key: "rye",
    disp: "Rye",
    cat: "spirit",
    color: "#C06A22",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["whiskey"],
  },
  {
    key: "saline solution",
    disp: "Saline solution",
    cat: "extract",
    color: "#DDE6EC",
    shape: "dropper",
    abv: 0,
    aliases: ["saline"],
  },
  {
    key: "salsa",
    disp: "Salsa",
    cat: "condiment",
    color: "#B5432E",
    shape: "jar",
    abv: 0,
  },
  {
    key: "scotch",
    disp: "Scotch",
    cat: "spirit",
    color: "#A85A1A",
    shape: "squircle",
    abv: 0.4,
    umbrellas: ["whiskey", "consumable"],
  },
  {
    key: "simple syrup",
    disp: "Simple syrup",
    cat: "syrup",
    color: "#DDE2E6",
    shape: "bottle",
    abv: 0,
    syrup: "simple",
    aliases: ["simple"],
    umbrellas: ["syrup"],
  },
  {
    key: "soda water",
    disp: "Soda water",
    cat: "mixer",
    color: "#DCE8EE",
    shape: "droplet",
    abv: 0,
    aliases: ["seltzer", "soda"],
    umbrellas: ["consumable"],
  },
  {
    key: "soy sauce",
    disp: "Soy sauce",
    cat: "condiment",
    color: "#3A2417",
    shape: "bottle",
    abv: 0,
    defaultLocation: "pantry",
  },
  {
    key: "spirit",
    disp: "Neutral spirit",
    cat: "spirit",
    color: "#E0E6EC",
    shape: "squircle",
    abv: 0.4,
  },
  {
    key: "sugar",
    disp: "Sugar",
    cat: "sugar",
    color: "#EDEAE0",
    shape: "cube",
    abv: 0,
    aliases: ["white sugar"],
  },
  {
    key: "sweet vermouth",
    disp: "Sweet vermouth",
    cat: "fortified",
    color: "#7A2E2E",
    shape: "glass",
    abv: 0.17,
    umbrellas: ["vermouth", "wine"],
  },
  {
    key: "syrup",
    disp: "Syrup",
    cat: "syrup",
    color: "#C9B98A",
    shape: "bottle",
    abv: 0,
    syrup: "generic",
  },
  {
    key: "tajín",
    disp: "Tajín",
    cat: "herbspice",
    color: "#BD4A2E",
    shape: "shaker",
    abv: 0,
    aliases: ["tajin"],
  },
  {
    key: "tequila",
    disp: "Tequila",
    cat: "spirit",
    color: "#E6E0AE",
    shape: "squircle",
    abv: 0.4,
    aliases: ["mezcal"],
    umbrellas: ["tequila", "agave", "consumable"],
  },
  {
    key: "tomato",
    disp: "Tomato",
    cat: "produce",
    color: "#C8402E",
    shape: "circle",
    abv: 0,
    aliases: ["tomatoes"],
  },
  {
    key: "tomato sauce",
    disp: "Tomato sauce",
    cat: "condiment",
    color: "#B0402A",
    shape: "cylinder",
    abv: 0,
    defaultLocation: "pantry",
  },
  {
    key: "tonic water",
    disp: "Tonic water",
    cat: "mixer",
    color: "#DCE8EE",
    shape: "droplet",
    abv: 0,
    aliases: ["tonic"],
    umbrellas: ["consumable"],
  },
  {
    key: "vegetable broth",
    disp: "Vegetable broth",
    cat: "drygood",
    color: "#B8954A",
    shape: "box",
    abv: 0,
    aliases: ["vegetable stock", "veggie stock", "broth", "stock"],
  },
  {
    key: "vegetable oil",
    disp: "Vegetable oil",
    cat: "drygood",
    color: "#CDB164",
    shape: "bottle",
    abv: 0,
  },
  {
    key: "veggie burgers",
    disp: "Veggie burgers",
    cat: "protein",
    color: "#7A5A33",
    shape: "patty",
    abv: 0,
    aliases: ["veggie burger"],
  },
  {
    key: "veggie chili",
    disp: "Veggie chili",
    cat: "drygood",
    color: "#8A4B2A",
    shape: "cylinder",
    abv: 0,
  },
  {
    key: "veggie sausage",
    disp: "Veggie sausage",
    cat: "protein",
    color: "#9B5A3A",
    shape: "patty",
    abv: 0,
    aliases: ["veggie sausages"],
  },
  {
    key: "whipped cream",
    disp: "Whipped cream",
    cat: "dairyegg",
    color: "#F5F1E6",
    shape: "shaker",
    abv: 0,
  },
  {
    key: "whiskey",
    disp: "Whiskey",
    cat: "spirit",
    color: "#B5651D",
    shape: "squircle",
    abv: 0.4,
    aliases: ["whisky"],
  },
  {
    key: "wine",
    disp: "Wine",
    cat: "fortified",
    color: "#7A2E3A",
    shape: "glass",
    abv: 0.12,
  },
  {
    key: "yellow chartreuse",
    disp: "Yellow Chartreuse",
    cat: "liqueur",
    color: "#D7C23A",
    shape: "hexagon",
    abv: 0.4,
    umbrellas: ["chartreuse"],
  },
];
