/* Generate src/ingredients-seed.ts from the recipe seed using the full parser.
 * Run: npm run gen:ingredients
 *
 * This is the ONLY place the classification regex (parser RULES) runs to define
 * ingredients. At runtime the app reads the emitted seed instead of re-deriving
 * the catalog from recipes. Re-run this whenever the canonical recipe seed or the
 * parser rules change. */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { seedRecords } from '../src/state';
import { parseLine, classify } from '../src/parser';
import { buildCatalog, ingredientKey } from '../src/ingredients';
import type { Classified } from '../src/types';

const recs = seedRecords();

// Catalog (stockable entries, generics excluded) + active umbrella set.
const cat = buildCatalog(recs);
const entries = cat.entries
  .map(e => ({ key: e.key, disp: e.disp, cat: e.cat, color: e.color, shape: e.shape, umbrella: e.umbrella }))
  .sort((a, b) => a.key.localeCompare(b.key));

// Per-key classification (incl. generics like "rum"/"spirit") for recipe-chip rendering,
// and a name -> key alias index for matching recipe text without the regex at runtime.
const classMap: Record<string, Classified> = {};
const aliases: Record<string, string> = {};
for (const rec of recs) {
  const p = parseLine(`${rec.name}: ${rec.recipe}`)!;
  for (const i of p.ingredients) {
    const key = ingredientKey(i);
    const c = classify(i.name); // strip the rule's `re` regex; keep only Classified fields
    classMap[key] = { cat: c.cat, shape: c.shape, color: c.color, abv: c.abv, disp: c.disp, fam: c.fam, syrup: c.syrup, citrus: c.citrus };
    aliases[i.name.toLowerCase()] = key;
  }
}

// Expand the common citrus garnish/juice forms so e.g. "lime peel" still matches
// even if only "lime wheel" appeared in the seed recipes.
for (const [key, c] of Object.entries(classMap)) {
  if (c.cat !== 'citrus') continue;
  for (const form of ['', ' juice', ' peel', ' wheel', ' twist', ' wedge', ' wedges']) {
    aliases[(key + form).trim()] = key;
  }
}

const sortedClass = Object.fromEntries(Object.entries(classMap).sort((a, b) => a[0].localeCompare(b[0])));
const sortedAliases = Object.fromEntries(Object.entries(aliases).sort((a, b) => a[0].localeCompare(b[0])));
const active = [...cat.active].sort();

const out = `// GENERATED by scripts/gen-ingredients.ts — do not edit by hand.
// Run \`npm run gen:ingredients\` to regenerate from the recipe seed.
import type { Classified } from './types';

export interface SeedEntry {
  key: string;
  disp: string;
  cat: string;
  color: string;
  shape: string | null;
  umbrella: string;
}

/** Stockable catalog ingredients (effective generics excluded). */
export const INGREDIENT_SEED: SeedEntry[] = ${JSON.stringify(entries, null, 2)};

/** Classification per ingredient key (incl. generic umbrellas), used to render
 *  recipe chips at runtime without running the parser regex. */
export const INGREDIENT_CLASS: Record<string, Classified> = ${JSON.stringify(sortedClass, null, 2)};

/** Structural-name -> key index for matching recipe text to the catalog. */
export const INGREDIENT_ALIASES: Record<string, string> = ${JSON.stringify(sortedAliases, null, 2)};

/** Umbrella keys that have at least one specific member (generic-match targets). */
export const ACTIVE_UMBRELLAS: string[] = ${JSON.stringify(active, null, 2)};
`;

const dest = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'ingredients-seed.ts');
writeFileSync(dest, out);
console.log(`Wrote ${dest}: ${entries.length} entries, ${Object.keys(sortedClass).length} classes, ${Object.keys(sortedAliases).length} aliases, ${active.length} active umbrellas.`);
